# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: listing dirs
      run: ls ./
    - name: "Prepare SSH key and known hosts"
      run: |
        mkdir -p ~/.ssh
        cat ./pruebas.pem  > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan git.eu.s5y.io >> ~/.ssh/known_hosts
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        ssh-host: ec2-18-216-9-188.us-east-2.compute.amazonaws.com
    - name: Deploy to AWS
      run: sh ./deploy/deploy.sh
      env: 
        SERVER: ec2-18-216-9-188.us-east-2.compute.amazonaws.com
    # - run: npm run build --if-present
